services:
  - type: web
    name: astrahealth-api
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_SECURE
        value: true
      - key: FRONTEND_ORIGIN
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false
      - key: MAIL_TO
        sync: false
